[project]
name = "xampp-devenv-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "mysql-connector-python>=9.3.0",
    "selenium>=4.33.0",
    "sqlalchemy>=2.0.41",
]
